### ISSUE TITLE
Week 5 - Proctored MCQ Week1

### ISSUE THREAD

**Issue by aaditgupta21** [aaditgupta21/csp-notes#8]
**Final Grade**

5/5 (0.5 is subject to teacher) (comments below)
Corrected by: Leo Sun

**Tasks**

- [x] GH Indi Page and Review Ticket for following...
- [x] Start review ticket with study plan and study reflection for week, due EOD Monday 4/18
- [x] Finals-Quiz1 score/50 and corrections
- [x] Finals-Quiz2 score/50 and corrections
- [x] Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permits
Evidence

[Github Pages](https://aaditgupta21.github.io/csp-notes/)
[Create Task](https://aaditgupta21.github.io/csp-notes/createtask)
[Quiz Scores + Corrections](https://aaditgupta21.github.io/csp-notes/prep/final1)
[Study Plan](https://github.com/aaditgupta21/csp-notes/issues/7)

**Comment by lleosunn** [comment]
study plan is on review ticket +1
github pages have scores and corrections + 1
quiz 1 and corrections are on github pages +1
quiz 2 and corrections are on github pages +1
create task code and runtime and responses are on github pages with all requirements met +1
final score: 5/5
